Todo#update の実装
chionyan/simple-todo-api pull request #10
Opened 2018-08-17 08:04 UTC by chionyan

このPRにおける目的
----
指定の Todo データを更新するための API を実装する。

やったこと
----
- `PATCH /todos/:id` のルーティング設定
- Todo#update の実装
- Request Spec の作成

動作確認
----

- [ ] Rails
  - `$ bin/setup` を実行
  - `$ bundle exec rails s` で Rails サーバーを起動
  - `id` 確認のため、新規レコードを作成する
  ```sh
  $ curl -X POST "http://localhost:3000/todos" -d "title=Sample title" -d "text=Sample text" 
  {
    "id": "47706e63-f3f6-41b4-930f-a41eb08b2e5c",
    "title": "Sample title",
    "text": "Sample text",
    "created_at": "2018-08-17T07:52:50Z"
  }
  ```

  - [ ] `http://localhost:3000/todos/:id` に対して下記コマンドを実行し、先ほど作成したレコードの `title` `text` が更新されて返ってくることを確認
  ```sh
  $ curl -X PATCH "http://localhost:3000/todos/47706e63-f3f6-41b4-930f-a41eb08b2e5c" -d "title=Change title" -d "text=Change text"
  {
    "id": "47706e63-f3f6-41b4-930f-a41eb08b2e5c",
    "title": "Change title",
    "text": "Change text",
    "created_at": "2018-08-17T07:52:50Z"
  }
  ```
- [ ] RSpec
  - `$ bundle exec rspec` を実行
  - [ ] `0 failures` が出力されることを確認
- [ ] Rubocop
  - `$ bundle exec rubocop` を実行
  - [ ] `no offenses detected` が出力されることを確認

このPRにおけるスコープ外
----

- 存在しない URL にアクセスした際のエラー処理は他PRで実装します。

2018-08-20 03:32 UTC, chionyan commented
@koshigoe @pokotyamu 
Todo#update の実装の PR 作成しました！レビューお願いします🙏✨

2018-08-20 06:09 UTC, pokotyamu commented
👀

2018-08-20 06:10 UTC, pokotyamu commented
> Todo#update の実装

0コメですが、やったことが `Todo` クラスの `#update` の実装になっているのあってますか？ 👀

2018-08-20 06:18 UTC, pokotyamu requested changes
レビューしました！
DRY になっていない部分が特に気になりました！

2018-08-20 06:18 UTC, pokotyamu commented on app/controllers/todos_controller.rb
> +    todo = Todo.find(params['id'])
`#show` のところでは1箇所しか出てこなかったので言わなかったんですが、ここのパラメーターから todo を撮ってくるメソッドが複数箇所で定義されているのが気になりますね 🤔 
DRY 原則を意識するとよりよくなるかと思いました 🙋‍♂️

2018-08-20 06:18 UTC, pokotyamu commented on spec/requests/todos_spec.rb
> +    subject { patch "/todos/#{todo.id}", params: params }
ちなみに HTTP メソッドの PUT と PATCH の違いはご存知ですか？ 😄

2018-08-20 06:24 UTC, chionyan commented on spec/requests/todos_spec.rb
> +    subject { patch "/todos/#{todo.id}", params: params }
PUT はレコード全体を更新、 PATCH はレコードを部分的に更新、ですかね👀？

2018-08-20 06:36 UTC, chionyan commented on app/controllers/todos_controller.rb
> +    todo = Todo.find(params['id'])
f0d7a0c で `#show` `#update` で行われているパラメータから todo を取ってくるメソッドを `#set_todo` にまとめました❗️

2018-08-20 06:38 UTC, pokotyamu commented on spec/requests/todos_spec.rb
> +    subject { patch "/todos/#{todo.id}", params: params }
合ってます 🙆‍♂️ 
Rails だと resource で update を指定すると PUT も PATCH も両方とも生えますが、使い分け的には冪等かどうかで判断するというのも１つですね。

Rails で PATCH が追加された経緯のやつ: [Edge Rails: PATCH is the new primary HTTP method for updates | Riding Rails](https://weblog.rubyonrails.org/2012/2/26/edge-rails-patch-is-the-new-primary-http-method-for-updates/)

2018-08-20 06:42 UTC, chionyan commented
> 0コメですが、やったことが Todo クラスの #update の実装になっているのあってますか？ 👀

```sh
$ be rails routes
Prefix Verb  URI Pattern          Controller#Action
 todos GET   /todos(.:format)     todos#index
       POST  /todos(.:format)     todos#create
  todo GET   /todos/:id(.:format) todos#show
       PATCH /todos/:id(.:format) todos#update
       PUT   /todos/:id(.:format) todos#update
```

となっていたので、 `todos#update` が正しいのですか？？？

2018-08-20 06:44 UTC, pokotyamu commented
あ、 `TodosController#update` かなぁという印象を受けただけでした 🙏

2018-08-20 06:45 UTC, pokotyamu commented
前回分でも、こう書いてたのか見落としてた 🙏

2018-08-20 06:57 UTC, chionyan commented
@pokotyamu 
指摘事項の修正完了しました！再度レビューお願いします(^o^)

2018-08-20 09:10 UTC, pokotyamu commented
```
$ curl -X POST "http://localhost:3000/todos" -d "title=Sample title" -d "text=Sample text" | jq .
{
  "id": "630cefeb-958d-4586-9126-bc60af46e6d0",
  "title": "Sample title",
  "text": "Sample text",
  "created_at": "2018-08-20T09:06:03Z"
}
$ curl -X PATCH "http://localhost:3000/todos/d4f90ebd-08f8-4c13-8c99-830e98d37529" -d "title=Chae title" -d "text=Change text" | jq .
{
  "id": "d4f90ebd-08f8-4c13-8c99-830e98d37529",
  "title": "Chae title",
  "text": "Change text",
  "created_at": "2018-08-20T09:02:40Z"
}
$ rails c
Todo.find('d4f90ebd-08f8-4c13-8c99-830e98d37529')
  Todo Load (0.4ms)  SELECT  "todos".* FROM "todos" WHERE "todos"."id" = $1 LIMIT $2  [["id", "d4f90ebd-08f8-4c13-8c99-830e98d37529"], ["LIMIT", 1]]
=> #<Todo:0x00007fe77069d598
 id: "d4f90ebd-08f8-4c13-8c99-830e98d37529",
 title: "Chae title",
 text: "Change text",
 created_at: Mon, 20 Aug 2018 09:02:40 UTC +00:00,
 updated_at: Mon, 20 Aug 2018 09:03:05 UTC +00:00>
```

良さそう 👌

2018-08-20 09:11 UTC, pokotyamu approved these changes
質問したとこは口頭で軽く補足しました 🙆‍♂️ 
LGTM！

2018-08-22 01:26 UTC, merged

2018-08-22 02:22 UTC, koshigoe commented on app/controllers/todos_controller.rb
>    end
❓200 OK で Location ヘッダを追加している目的って何かありますか？

2018-08-22 02:35 UTC, chionyan commented on app/controllers/todos_controller.rb
>    end
ちょっとソースがどこか思い出せないので申し訳ないのですが、 `#update` 処理にも Location ヘッダーを付けると書いてあったのを鵜呑みにしてしまいました…。
[RESTful API設計におけるHTTPステータスコードの指針 \- Qiita](https://qiita.com/uenosy/items/ba9dbc70781bddc4a491)に書いてある、 `PUT` の場合の作成・更新処理両方のことを指していたのかもしれません。

2018-08-22 02:48 UTC, koshigoe commented on app/controllers/todos_controller.rb
> +    todo = Todo.find(params['id'])
(余計な事を書いて混乱させてしまう気がしつつ、勢いで書いてしまう 🙇🙇🙇🙇🙇🙇🙇🙇)

> DRY

コードの字面的に同等だという理由で(脊髄反射的に)共通化するのではなく、意味的に同一だから共通化する(してよい)、という考え方をすべきなので、なかなか難しい所ですね。 🤔 
また、(設計上の)決定を送らせるために、敢えてコードを重複させるという決断をする事もあるので、更に悩ましいところです。🤔🤔

RESTful API の事を考える場合、 `/todos/:id` という同一のエンドポイント(URI)においては必ずリソースを特定(読み出し)すると考えると、その処理を共通化するのは妥当かと思います。
ただし、同一エンドポイントにおいても HTTP メソッドによっては、前処理や後処理、エラー処理などが異なる場合、敢えて重複して見える実装とする事もあるかと思います。