ActiveRecord:: RecordInvalid 例外処理の実装
chionyan/simple-todo-api pull request #16
Opened 2018-08-23 09:10 UTC by chionyan

このPRにおける目的
----
[WIP]

やったこと
----
[WIP]

動作確認
----

- [ ] RSpec
  - `$ bundle exec rspec` を実行
  - [ ] `0 failures` が出力されることを確認
- [ ] Rubocop
  - `$ bundle exec rubocop` を実行
  - [ ] `no offenses detected` が出力されることを確認

このPRにおけるスコープ外
----

2018-08-23 10:06 UTC, chionyan commented
(口頭説明)
[MakeShop 初回連携 API](https://github.com/feedforce/dfplusio-api/wiki/%E4%BB%95%E6%A7%98%EF%BC%9AMakeShop-%E9%80%A3%E6%90%BA%E6%A9%9F%E8%83%BD#user-content-makeshop-%E5%88%9D%E5%9B%9E%E9%80%A3%E6%90%BA-api)のように
```
{
  "data": {
    "attributes": {
      "title": "タイトル",
      "text": "テキスト"
    }
  }
}
```
をリクエストパラメータとして送った結果、 `"pointer": "/data/attributes/{attribute name}"` が返ってくるものだと考えられる。
したがって、リクエストパラメータとして送るデータの階層が異なると、 `pointer` として返ってくる階層も違ってくる。

2018-08-28 06:13 UTC, chionyan commented
## 動作確認
### Rails
したがって、RecordInvalid 例外処理の返却値は以下の通りとなる。
また、リクエストボディは `{ "title": "...", "text": "..." }` の形式に限る。

### `title` が空文字の時
- `$ curl -X POST "http://localhost:3000/todos" -d "title=" -d "text=Sample text 1" | jq`
- `$ curl -X POST "http://localhost:3000/todos" -H "Content-Type: application/json" -d '{"title":"", "text": "Sample text 1"}' | jq`
```json
{
  "errors": [
    {
      "title": "バリデーションに失敗しました。",
      "status": 422,
      "source": {
        "pointer": "/title"
      }
    }
  ]
}
```

### `text` が空文字の時
- `$ curl -X POST "http://localhost:3000/todos" -d "title=Sample title 1" -d "text=" | jq`
- `$ curl -X POST "http://localhost:3000/todos" -H "Content-Type: application/json" -d '{"title":"Sample title 1", "text": ""}' | jq`
```json
{
  "errors": [
    {
      "title": "バリデーションに失敗しました。",
      "status": 422,
      "source": {
        "pointer": "/text"
      }
    }
  ]
}
```

### `title` `text` が空文字の時
- `$ curl -X POST "http://localhost:3000/todos" -d "title=" -d "text=" | jq`
- `$ curl -X POST "http://localhost:3000/todos" -H "Content-Type: application/json" -d '{"title":"", "text": ""}' | jq`
```json
{
  "errors": [
    {
      "title": "バリデーションに失敗しました。",
      "status": 422,
      "source": {
        "pointer": "/title"
      }
    },
    {
      "title": "バリデーションに失敗しました。",
      "status": 422,
      "source": {
        "pointer": "/text"
      }
    }
  ]
}
```

2018-08-28 06:50 UTC, chionyan commented
@koshigoe @pokotyamu 
`todos#create` `todos#update` におけるバリデーションエラーの例外処理のテストのPRを作成しました！レビューお願いします🙏
実装における決定事項などは、[Issue \#18](https://github.com/chionyan/simple-todo-api/issues/18#issuecomment-416460609)に記述していますので、一度目を通していただけるとと思います🙇‍♀️

2018-08-28 06:59 UTC, koshigoe commented
👁

2018-08-28 07:13 UTC, koshigoe reviewed
取り急ぎ、ざっくりとした感想まで。

2018-08-28 07:13 UTC, koshigoe commented on app/controllers/todos_controller.rb
> +
❓バリデーション違反の原因に関わらず、 `/errors/i/title` の値が `"バリデーションに失敗しました。"` 固定である理由を知っておきたいです。利用者としては、具体的にどういう理由で受け入れられなかったのかを知りたいかと思うのですが、敢えて詳細な情報は伝えないポリシーという事でしょうか？

2018-08-28 07:13 UTC, koshigoe commented on app/controllers/todos_controller.rb
> +
❓バリデーション違反のメッセージを使わないのであれば、[`ActiveModel::Errors#keys`](https://api.rubyonrails.org/classes/ActiveModel/Errors.html#method-i-keys)を使えば良さそうに見えますが、そんなことないですかね？

2018-08-28 07:13 UTC, koshigoe commented on app/controllers/todos_controller.rb
> +
❓余談(感想)ですが `map` を使えばブロックの中で `<<` する必要がなくなるかなと思いました。

2018-08-28 07:13 UTC, koshigoe commented on app/controllers/todos_controller.rb
> +
❓これも余談ですが、 キー `'pointer'` はシンボルでなく文字列なんですね。

2018-08-28 07:13 UTC, koshigoe commented on app/controllers/todos_controller.rb
> +
❓さらに感想ですが、「バリデーションに失敗しました」という日本語を読んで、バリデーション処理が正常に行えなかったのか、入力値がバリデーションルールに違反していたのか、よく分からないなと思いました。が、これは、自分の日本語能力の問題な気もします。

2018-08-28 07:25 UTC, chionyan commented on app/controllers/todos_controller.rb
> +
> 余談(感想)ですが map を使えばブロックの中で << する必要がなくなるかなと思いました。

🅰️ こちらはうまいこと書き換えれそうな気がしますので、修正してみます！

> これも余談ですが、 キー 'pointer' はシンボルでなく文字列なんですね。

🅰️ こちらはうっかりミスだったので修正します😂

> バリデーション違反のメッセージが固定である件について

🅰️ Swagger の仕様で `"title": "..."` となっていて何を入れたらいいかわからなかったので、とりあえず固定のメッセージを入れていました。ただ実装しながら、コメントいただいた通り、自分がユーザ目線だった場合に何がエラーなのかわからないので、このPR内でエラーメッセージを具体的にする修正を行います❗️

2018-08-28 08:44 UTC, chionyan commented on app/controllers/todos_controller.rb
> +
バリデーション違反のメッセージについては、 eef84da で ActiveRecord の日本語辞書を追加し、 
4474977 で詳細なメッセージを表示しています！
`pointer` のシンボルの件や、 `#map` 使って配列を書き換える修正も 4474977 で行なっています！
ついでに `i18n` の翻訳で行が長くなることなどから、メソッドを切り出して、 NotFound の方も 
91c22b6 で修正しています✨

2018-08-29 00:33 UTC, koshigoe reviewed
改めてコメントしました。

質問について、意図的な仕様だったり、意識的なスタイルだ、という事であれば特に修正せずそのままで良いかと思いました。

2018-08-29 00:33 UTC, koshigoe commented on app/controllers/todos_controller.rb
> +
❓ ActiveModel のバリデーション機能で得られるエラーメッセージを使っていないのは意図しての事ですか？

> i18n の翻訳で行が長くなることなどから、メソッドを切り出し

`ActiveModel::Errors` によるメッセージの組み立てで内部的に `I18n` が使われている事はご存じです？

- :bookmark: https://guides.rubyonrails.org/i18n.html#translations-for-active-record-models
- :bookmark: https://github.com/rails/rails/blob/184c1a405f58b069e0b9ef79a2ad67f7d7d9e69b/activemodel/lib/active_model/errors.rb
- :bookmark: https://github.com/rails/rails/blob/184c1a405f58b069e0b9ef79a2ad67f7d7d9e69b/activemodel/lib/active_model/locale/en.yml
- :bookmark: https://github.com/svenfuchs/rails-i18n/blob/2fbcb49765d09b17ccee204be96b17ff888beeec/rails/locale/ja.yml

```
5.2.1@2.5.0 (main)> todo = Todo.new
=> #<Todo:0x00007fd5ca9b4d38 id: nil, title: nil, text: nil, created_at: nil, updated_at: nil>
5.2.1@2.5.0 (main)> todo.validate
=> false
5.2.1@2.5.0 (main)> todo.errors.full_messages
=> ["Title can't be blank", "Text can't be blank"]
5.2.1@2.5.0 (main)> todo.errors.messages
=> {:title=>["can't be blank"], :text=>["can't be blank"]}
5.2.1@2.5.0 (main)> I18n.with_locale(:ja) { todo.errors.full_messages }
=> ["タイトル can't be blank", "テキスト can't be blank"]
5.2.1@2.5.0 (main)> I18n.with_locale(:ja) { todo.errors.messages }
=> {:title=>["can't be blank"], :text=>["can't be blank"]}
```

2018-08-29 00:33 UTC, koshigoe commented on app/controllers/todos_controller.rb
> +
> e.record.errors.messages.keys

🤔 バリデーション違反の属性名が必要なだけであれば `ActiveModel::Errors#message` を経由せず `ActiveModel::Errors#keys` で良かったりしませんか？(https://github.com/chionyan/simple-todo-api/pull/16#discussion_r213204449)

> errors.map!

🤔 変数 `errors` に代入してから `map!` するくらいなら、 `errors = e.record.errors.keys.map do |attribute|` で良かったりしませんか？

2018-08-29 05:47 UTC, chionyan commented on app/controllers/todos_controller.rb
> +
> ActiveModel のバリデーション機能で得られるエラーメッセージを使っていないのは意図しての事ですか？
> ActiveModel::Errors によるメッセージの組み立てで内部的に I18n が使われている事はご存じです？
🅰️ こちらについては、 gem `rails-i18n` をインストールし `default_locale = :ja` とした上で、`ActiveModel::Errors` からメッセージを取得します！

2018-08-29 06:27 UTC, chionyan commented on app/controllers/todos_controller.rb
> +
- `rails-i18n` のインストールは f721e5a 
- `default_locale = :ja` の設定は 548a666 
- `errors` の組み立てについては 10f2f6d
で修正しております✨

2018-08-29 06:28 UTC, chionyan commented
@koshigoe 
指摘事項の修正が完了しましたので、再度レビューお願いします🙏
@pokotyamu 
昨日少し見ていただいた部分からちょっと変更点などもあるので（切り出したメソッドの削除など）、もう一度見ていただいて何かあればご指摘お願いします✨

2018-08-30 02:42 UTC, koshigoe requested changes
バリデーションのエラーメッセージを取り出すロジックについて、コメントしました。

2018-08-30 02:42 UTC, koshigoe commented on app/controllers/todos_controller.rb
> +
任意の属性に関するバリデーションメッセージを取得する場合、属性名を指定すべきだと思います。

- [`ActiveModel::Errors#full_messages_for`](https://api.rubyonrails.org/classes/ActiveModel/Errors.html#method-i-full_messages_for)

`ActiveModel::Errors#full_messages[i]` がどの属性のメッセージを意味するかは、 `ActiveModel::Errors#keys` のインデックスから安定的に特定可能ではないと思います。
ActiveModel の仕組み上、ある属性に対するバリデーションエラーメッセージはひとつだとは限らないため、その仕組みを前提としたロジックであるべきだというのが、私の考えです。

2018-08-30 03:33 UTC, chionyan commented on app/controllers/todos_controller.rb
> +
コメントありがとうございます✨
`ActiveModel::Errors#full_messages_for` の存在を知らなかったので、インデックスを使うより属性を使って取り出した方が確実なメッセージを取り出せるとわかりました！
ac25274 で `ActiveModel::Errors#full_messages_for(attribute)` を使用してメッセージを取り出す方法に修正しました！ `full_messages_for` の戻り値のクラスが `Array` なのでそちらも分解して取り出せるように `#map` で回してます！

2018-08-30 03:40 UTC, koshigoe approved these changes
ループのネストが若干気になるけど、代替案がぱっと思いつかない。

仕組みとしては問題ないかなと思いました。

2018-08-30 09:02 UTC, merged