Todo#show の実装
chionyan/simple-todo-api pull request #9
Opened 2018-08-17 06:32 UTC by chionyan

このPRにおける目的
----
指定の Todo をデータするための API を実装する。

やったこと
----
- `GET /todos/{todo_id}` のルーティング設定
- Todo#index の実装
- Todo#create のレスポンスに Location を追加
- Request Spec の作成

動作確認
----

- [ ] Rails
  - `$ bin/setup` を実行
  - `$ bundle exec rails s` で Rails サーバーを起動
  - url 確認のため、一度新規レコードを作成する
  ```sh
  $ curl -X POST "http://localhost:3000/todos" -d "title=Sample title" -d "text=Sample text" 
  {
    "id": "2c63a32b-a5ca-4bc8-aa5f-c765ad573f09",
    "title": "Sample title",
    "text": "Sample text",
    "created_at": "2018-08-17T06:27:04Z"
  }
  ```

  - [ ] `http://localhost:3000/todos/{id}` に対して下記コマンドを実行し、先ほど作成したレコードが返ってくることを確認
  ```sh
  $ curl -X GET "http://localhost:3000/todos/2c63a32b-a5ca-4bc8-aa5f-c765ad573f09"
  {
    "id": "2c63a32b-a5ca-4bc8-aa5f-c765ad573f09",
    "title": "Sample title",
    "text": "Sample text",
    "created_at": "2018-08-17T06:27:04Z"
  }
  ```

- [ ] RSpec
  - `$ bundle exec rspec` を実行
  - [ ] `0 failures` が出力されることを確認
- [ ] Rubocop
  - `$ bundle exec rubocop` を実行
  - [ ] `no offenses detected` が出力されることを確認

このPRにおけるスコープ外
----
- 存在しない URL にアクセスした際のエラー処理は他PRで実装します。

2018-08-17 06:38 UTC, chionyan commented
@koshigoe @pokotyamu 
Todo#show の実装の PR 作成しました！レビューお願いします🙏✨

2018-08-17 06:44 UTC, pokotyamu commented
👀

2018-08-17 06:50 UTC, pokotyamu commented
> GET /todos/{todo_id} のルーティング設定

これ `/todos/:id` ですよね？

```
$ rails routes
Prefix Verb URI Pattern          Controller#Action
 todos GET  /todos(.:format)     todos#index
       POST /todos(.:format)     todos#create
  todo GET  /todos/:id(.:format) todos#show
```

2018-08-17 07:19 UTC, pokotyamu requested changes
テストの書き方が気になったぐらいでほかは大丈夫そうに思いました 👌

2018-08-17 07:19 UTC, pokotyamu commented on spec/requests/todos_spec.rb
> +        'created_at' => '2019-01-01T00:00:00Z',
`travel_to` をトップレベルに書いてるのか。
たしかに共通で使うからって意味ではいいけど、定義と離れすぎるのはあまり良くない気がします。あれ？これどこで設定してたっけ？みたいなのが分からなくなるため
特に、時間を扱う `travel_to` や `let!` などの定義は `describe` ぐらいでとどめておくのが良さそうに思いました。

2018-08-17 07:42 UTC, chionyan commented on spec/requests/todos_spec.rb
> +        'created_at' => '2019-01-01T00:00:00Z',
a9e42c7 で必要な `describe` の中にのみ記述するように修正しました！
各 `describe` 内で `let!` でレコードを作成しているため、 `let!` より前に記述しています！！

2018-08-17 07:45 UTC, chionyan commented
ルーティングについて説明のある0コメの修正、
Request Spec における `it` の説明について、
9d4060c で `GET /todos/:id` に修正しています！

2018-08-17 07:46 UTC, chionyan commented
@pokotyamu 
指摘事項について修正しましたので、再度レビューお願いします😆

2018-08-20 03:07 UTC, pokotyamu approved these changes
よさげ 👌 
LGTM 👌

2018-08-20 03:13 UTC, merged

2018-08-22 02:18 UTC, koshigoe commented
:memo:

> #8のコメントで指摘のあった Todo#create のレスポンスに Location を追加

💭 実際のプロダクトで PR つくる時は、これだけの PR を作ってもらう事になると思いました。